spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 5MB

springdoc:
  swagger-ui:
    path: /swagger-town-scoop.html
    tagsSorter: alpha
    operationsSorter: alpha

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: ${PORT:8080}
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    yapp: INFO

#ip:
#  town-scoop: ${SERVER_IP}