spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    activate:
      on-profile: common

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 15
      maximum-pool-size: 20
      connection-timeout: 3000
      validation-timeout: 1000
      max-lifetime: 600000
      connection-test-query: select 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
        rewriteBatchedStatements: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 5MB

springdoc:
  swagger-ui:
    path: /swagger-town-scoop.html
    tagsSorter: alpha
    operationsSorter: alpha

server:
  tomcat:
    threads:
      max: 20
      min-spare: 10
    accept-count: 100
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: ${PORT:8080}
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    yapp: INFO

#ip:
#  town-scoop: ${SERVER_IP}