spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: ${SERVER_IP_ONLY}
    port: ${REDIS_PORT}
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URL}
            client-authentication-method: POST
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

social-kakao:
  clientId: ${CLIENT_ID}
  redirectUri: ${KAKAO_REDIRECT_URL}
  clientSecret: ${CLIENT_SECRET}

app:
  auth:
    tokenSecret: ${APP_TOKEN_SECRET}
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - ${KAKAO_REDIRECT_URL}

cors:
  allowed-origins: ${ALLOWED_ORIGIN},${ALLOWED_REDIS_ORIGIN},http://localhost:8080,http://localhost:6379,https://townscoop.site
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

prod:
  host: ${ALLOWED_ORIGIN}