spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: ${REDIS_PORT}
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            client-authentication-method: POST
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

social-kakao:
  clientId: ${CLIENT_ID}
  redirectUri: http://localhost:8080/oauth2/callback/kakao
  clientSecret: ${CLIENT_SECRET}

cors:
  allowed-origins: http://localhost:8080,http://localhost:6379
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

app:
  auth:
    tokenSecret: ${APP_TOKEN_SECRET}
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/callback/kakao

logging:
  level:
    org:
      hibernate:
        type: trace