name: Townscoop CI/CD
on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ios1teamyapp21/yapp21-ios1-team:latest
          platform: linux/amd64
      
      - name: Install and configure AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      
      - name: Deploy to AWS CodeDeploy
        env:
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name yapp-townscoop-be \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name yapp-townscoop-group \
          --description "Deployment triggered from GitHub Actions" \
          --revision revisionType=Docker,imageName=ios1teamyapp21/yapp21-ios1-team:latest
